export const surfaces = {
  tech:{name:'aedae.tech',accent:'var(--tech)',glyph:'æDæ',role:'product / technical authority',state:'specified',title:'A personal authenticator for This PC',lead:'A Windows personal authenticator being specified with the gates on. Nothing is available to install yet.',facts:[['What is true now','The repository contains a bootstrap COM skeleton, package layout, and contract checks. Those items remain in review.','verified','README.md; tasks.md'],['What is specified','The design calls for local credential storage, Windows Hello verification before assertions, and fail-closed request handling. None of those capabilities is implemented.','specified','security.md; functional.md; tasks.md'],['What remains open','The public plugin contract does not define the operation-signing envelope needed to complete request-authentication design.','research','tasks.md T-019; reports/operation-signature-gate-design.md']],links:[['this-pc','This PC, in plain language'],['security','Security boundaries'],['build','Build gates'],['colophon','Colophon']]},
  world:{name:'aedae.world',accent:'var(--world)',glyph:'æDæ',role:'thesis / research horizon',state:'horizon',title:'Tools that leave more of you in your hands',lead:'æDæ begins with identity. Its wider direction is practical capability without needless surrender, extraction, or gatekeeping.',facts:[['The direction','Local-first tools can make more room for autonomy, dignity, and informed choice. This is an intention, not a product roadmap.','horizon','aedae venture positioning; public direction'],['The test','A future direction earns its place only if it improves real capability without making access conditional on surveillance or status.','horizon','aedae venture positioning'],['The limit','No funding, staffing, launch date, or market outcome is implied here.','verified','tasks.md; current repository state']],links:[['horizons','Read the horizons'],['colophon','Colophon']]},
  life:{name:'aedae.life',accent:'var(--life)',glyph:'æDæ',role:'practical capability / practice',state:'practice',title:'Small practices for keeping agency close',lead:'Vendor-neutral notes about recovery, access, and understanding your own systems. These are practices, not æDæ product claims.',facts:[['Keep recovery legible','Write down which recovery paths you control, then test one before you need it.','practice','general account-recovery practice, not sourced from the aeDae repository'],['Separate convenience from custody','A convenient sign-in flow may still depend on someone else holding the recovery path. Learn which is which.','practice','general digital-literacy practice, not sourced from the aeDae repository'],['Name the blind spots','No dashboard can automatically show every credential held by every provider. Treat a missing view as a limit, not proof.','practice','general passkey ecosystem limitation, not sourced from the aeDae repository']],links:[['colophon','What practice means here']]},
  live:{name:'aedae.live',accent:'var(--live)',glyph:'æDæ',role:'field notes / experiments',state:'research',title:'A place for work in motion',lead:'Experiments, decisions, and interruptions. This surface does not pretend that activity is progress.',facts:[['First note','The authenticator protocol lane is paused pending a stable, public answer about operation signing. Stopping is part of the record.','research','tasks.md T-019; reports/operation-signature-gate-design.md'],['What belongs here','Real notes: decisions, test results, reversals, and unanswered questions.','horizon','aedae web information architecture'],['What does not','Artificial cadence, manufactured demos, or a feed maintained only to appear alive.','verified','current public-site policy']],links:[['n001-stopping','Note 001: stopping'],['colophon','Colophon']]},
  online:{name:'aedae.online',accent:'var(--online)',glyph:'æDæ',role:'directory / entry point',state:'horizon',title:'Find the right aeDae surface',lead:'A quiet directory for an institution that may grow in several directions without becoming several disconnected brands.',facts:[['Technical product state','Product, security, and build claims are authoritative on aedae.tech only.','verified','aedae web information architecture'],['The present directory','The five surfaces are public roles, not five independent products.','verified','aedae web information architecture'],['The future','This may become a platform entry point only if a real platform exists and earns the added complexity.','horizon','aedae web information architecture']],links:[['colophon','Colophon']]}
};

const body = (surface, page, content='') => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${surface.lead}"><title>${surface.name} — ${surface.title}</title><link rel="stylesheet" href="/assets/styles.css"></head><body style="--accent:${surface.accent}"><a class="skip" href="#main">Skip to content</a><div class="shell"><nav class="nav" aria-label="aeDae surfaces"><a class="mark" href="/" aria-label="aeDae">æDæ</a>${Object.values(surfaces).map(s=>`<a ${s.name===surface.name?'aria-current="page"':''} href="/${s.name.replace('aedae.','')}/">${s.name}</a>`).join('')}</nav><main id="main">${content}</main><footer>Product state, security claims, and build status are authoritative on <a href="/tech/">aedae.tech</a> only. This site sets no cookies, uses no analytics, and has no third-party embeds.</footer></div></body></html>`;
const chip=(s,src)=>`<span class="status ${s}">${s}</span><p class="source">source: ${src}</p>`;
export function render(surfaceKey,page){const s=surfaces[surfaceKey];let extra='';if(page==='security')extra='<section class="section"><h2>Security boundaries</h2><p>Private keys, Windows Hello invocation, credential registration, and signing paths are not implemented. The project must fail closed when those paths are eventually considered.</p>'+chip('specified','security.md; tasks.md')+'</section>';
if(page==='build')extra='<section class="section"><h2>Gates before protocol work</h2><p>The local lane may proceed with synthetic records and mock UI. The protocol lane is paused pending T-019. A pause is not a delivery date.</p>'+chip('research','tasks.md T-019')+'</section>';
if(page==='this-pc')extra='<section class="section"><h2>Where it would sit</h2><p>Browser → Windows WebAuthn broker → æDæ plugin → Windows verification → local vault. This is the intended architecture, not a live flow.</p>'+chip('specified','architecture.md; functional.md')+'</section>';
if(page==='security')extra+='<p>The locked local Windows SDK exposes <code>webauthnplugin.h</code>. Header presence does not establish a supported operation-signing envelope.</p>'+chip('verified','reports/sample-mapping.md; reports/webauthnplugin-contract.md');
if(page==='build')extra+='<p>The contract verifier checks the locked plugin headers and recorded hashes. That verifies the build contract only; it does not resolve operation signing.</p>'+chip('verified','reports/webauthnplugin-contract.md; reports/webauthnplugin-abi-manifest.json');
if(page==='horizons')extra='<section class="section"><h2>What would have to be true</h2><p>A stable platform path, demonstrated user need, maintainable security practice, and a way to extend capability without making people surrender data or agency.</p>'+chip('horizon','aedae venture positioning')+'</section>';
if(page==='n001-stopping')extra='<section class="section"><h2>Note 001: stopping</h2><p>The public headers do not define the operation-signing envelope. The responsible action is to keep protocol work paused until the question is resolved or recorded as unavailable.</p>'+chip('research','tasks.md T-019')+'</section>';
if(page==='colophon')extra='<section class="section"><h2>Colophon</h2><p>This website is static. It sets no cookies, writes no local storage, runs no analytics, and embeds no third-party content. That describes this website, not unshipped software.</p>'+chip('verified','aedae web public-site policy')+'</section>';
const home=`<section class="hero"><div><h1>${s.glyph}</h1><p>${s.lead}</p>${chip(s.state, s.state==='practice'?'general practice, not an aeDae product claim':'see claim registry')}</div><div><div class="specimen" role="img" aria-label="${s.name} glyph construction specimen"><span class="glyph">${s.glyph}</span></div><p class="metrics">role: ${s.role} / anchors: 24·56·104 / state: ${s.state}</p></div></section><section class="section"><h2>${s.title}</h2><div class="grid">${s.facts.map(([h,p,st,src])=>`<article class="item"><h3>${h}</h3><p>${p}</p>${chip(st,src)}</article>`).join('')}</div></section><section class="section"><h2>Continue</h2><p>${s.links.map(([path,label])=>`<a href="/${surfaceKey}/${path==='colophon'?'colophon/':path+'/'}">${label}</a>`).join(' · ')}</p></section>`;return body(s,page,page==='index'?home:extra||`<section class="section"><h1>${page}</h1><p>This page is intentionally reserved for a sourced, reviewable record.</p></section>`)}
